# Generated by Django 3.0.1 on 2020-04-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactusform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTNAME', models.CharField(max_length=350)),
                ('LASTNAME', models.CharField(max_length=350)),
                ('PHONENO', models.CharField(max_length=150)),
                ('EMAIL', models.CharField(max_length=150)),
                ('MESSAGE', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaderform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTNAME', models.CharField(max_length=350)),
                ('LASTNAME', models.CharField(max_length=350)),
                ('QUALIFICATION', models.CharField(max_length=150)),
                ('PHONENO', models.CharField(max_length=150)),
                ('EMAIL', models.CharField(max_length=150)),
                ('COUNTRY', models.CharField(max_length=150)),
                ('RESUMEUPLOAD', models.CharField(max_length=150)),
            ],
        ),
    ]
